version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-bill-data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bill_data
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "hieunk", "-p123456"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local